//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace spider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDAEntities1 : DbContext
    {
        public MDAEntities1()
            : base("name=MDAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<電影圖片總表MovieImages> 電影圖片總表MovieImages { get; set; }
        public virtual DbSet<電影Movies> 電影Movies { get; set; }
        public virtual DbSet<電影排行MovieRank> 電影排行MovieRank { get; set; }
    }
}
