//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace spider
{
    using System;
    using System.Collections.Generic;
    
    public partial class 導演總表Director
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 導演總表Director()
        {
            this.電影導演MovieDirector = new HashSet<電影導演MovieDirector>();
        }
    
        public int 導演編號Director_ID { get; set; }
        public string 導演中文名字Name_Cht { get; set; }
        public string 導演英文名字Name_Eng { get; set; }
        public string 導演照片Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<電影導演MovieDirector> 電影導演MovieDirector { get; set; }
    }
}
