//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace spider
{
    using System;
    using System.Collections.Generic;
    
    public partial class 電影Movies
    {
        public int 電影編號Movie_ID { get; set; }
        public Nullable<int> 系列編號Series_ID { get; set; }
        public string 中文標題Title_Cht { get; set; }
        public string 英文標題Title_Eng { get; set; }
        public int 上映年份Release_Year { get; set; }
        public string 上映日期Release_Date { get; set; }
        public Nullable<int> 片長Runtime { get; set; }
        public int 電影分級編號Rating_ID { get; set; }
        public Nullable<decimal> 評分Rate { get; set; }
        public Nullable<decimal> 期待度anticipation { get; set; }
        public string 票房BoxOffice { get; set; }
        public string 劇情大綱Plot { get; set; }
        public string 預告片Trailer { get; set; }
    }
}
