//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace spider
{
    using System;
    using System.Collections.Generic;
    
    public partial class 電影圖片總表MovieImages
    {
        public int 圖片編號Image_ID { get; set; }
        public string 圖片Image { get; set; }
        public string 圖片雲端ImageIMDB { get; set; }
        public string 圖片類型ImageType { get; set; }
        public string 電影名稱MovieName { get; set; }
        public Nullable<int> 屏蔽Invisible { get; set; }
    }
}
